### ISSUE TITLE
Listener spec seems todo nothing.

### ISSUE THREAD

**Issue by alieander** [fastly/fastly_nsq#27]
https://github.com/fastly/fastly_nsq/blob/master/spec/lib/fastly_nsq/message_queue/listener_spec.rb#L71-L94

This spec passes with or without the code in https://github.com/fastly/fastly_nsq/blob/master/lib/fastly_nsq/message_queue/listener.rb#L9-L15

**Comment by alieander** [comment]
@adarsh

**Comment by adarsh** [comment]
Agree. This is hard to test because the `SIGINT` will kill the test process as well, so you can't really assert anything that well.

May be worth removing this or asserting that `.terminate` gets sent to the  `MessageQueue::Consumer#connection`.
