### ISSUE TITLE
We should use NSQ_LOOKUPD to produce as well

### ISSUE THREAD

**Issue by alieander** [fastly/fastly_nsq#28]
https://github.com/fastly/fastly_nsq/blob/master/lib/fastly_nsq/message_queue/producer.rb#L28
This should point at a producer

**Comment by adarsh** [comment]
Agree 👍

**Comment by adarsh** [comment]
Noted this in ticket `HYD-1168` (will not link here, since this is a public repo).

**Comment by alieander** [comment]
This appears to no longer make any sense!
