### ISSUE TITLE
[RFC] Use JSON schemata to validate messages before publishing

### ISSUE THREAD

**Issue by adarsh** [fastly/fastly_nsq#31]
# Request for Comments

Reason for Change
=================
* We are adhering to a loose convention for the JSON messages published to our NSQ: something like `{ 'data': { 'key1': 'value1', 'key2': 'value2' }, 'meta': { blah }`
* This is all well and good, but we aren't enforcing this for published messages.
* Again, this is no problem until this structure drifts and the downstream message processors dislike a change in the structure which they may depend on. 

Proposed Changes
===============
* Implement an optional [JSON Schema] directory like `/lib/message_queue/schemata` into which some schema files can go.
* Then, when publishing a message to a particular topic, such as `fastly_customer_created`, we could check for a `fastly_customer_created.json` schema.
* If a matching schema exists, we can run it against the message to ensure fidelity. If it fails, error out (or warn/log).
* If no schema matches, carry on happily with message publishing.
* Maybe have an optional `general.json` schema, into which can cover more broad structural specifications like [JSON API], which we are trending toward across the org.

[JSON Schema]:  http://json-schema.org/
[JSON API]: http://jsonapi.org/

Comments?

**Comment by jaw6** [comment]
My gut reaction is that JSON Schemata feels like a heavy, outside standard for a project this young. Are there non-Ruby consumers/producers (yet) ? If there are (or are likely to be?) maybe a JSON schemata is valuable (as it is language portable). If there aren't, maybe we can standardize around a `Message` (or similar name) instead. I guess I have a preference for using Ruby first, if possible.

**Comment by leklund** [comment]
I think we should continue to use the loose convention as it evolves we can draft JSON Schema definitions based on the convention. Trying to define it now and enforce it now seems like it might cost more time and effort than it's worth.

**Comment by adarsh** [comment]
I'm going to close this issue for now based on the responses to-date. Thanks for input, all!

**Comment by adarsh** [comment]
Note from @ezkl for posterity:

> if/when we come back to it, Heroku’s tooling is great: https://github.com/interagent/prmd
